### ISSUE TITLE
Using slack for conversations

### ISSUE THREAD

**Issue by elmerland** [andromedai/andromedai#22]
Hey quinn, so I recently came across this site called [slack](https://slack.com/). You know how I mentioned earlier that it would be cool to have a place to discuss new features or plans for the project without having to create issues for it? Well, slack could be used for that. We still have the github issues for actual bugs in the program, but we can use slack to discuss possible features and changes. Check it out and let me know what you think. I also created a team page https://andromedai.slack.com/. I will send you an invite shortly so that you can check it out!

**Comment by quinnliu** [comment]
@elmerland I never recieved an invitation. Would you mind resending it to quinnliu@vt.edu?

**Comment by quinnliu** [comment]
For now I don't think there is a need for slack as there are more important things to focus on. Maybe when we have a team of 5+ developers. Github issues works fine for now.
