### ISSUE TITLE
GitFlow branch scheme

### ISSUE THREAD

**Issue by elmerland** [andromedai/andromedai#6]
Consider using the branching model described [here](http://nvie.com/posts/a-successful-git-branching-model/). If we adopt that branching scheme we could use the [gitflow](https://github.com/nvie/gitflow) plugin to make things easier for new developers.

**Comment by quinnliu** [comment]
We are just going to use the guide I wrote [here](https://github.com/WalnutiQ/WalnutiQ/issues/62) and the 1.5 hour git tutorials I made [here](https://www.youtube.com/watch?v=44E8o-xuxWo&list=PLPXsMt57rLtgpwFBqZq4QKxrD9Hhc_8L4)
